import type { Client, ProcessDetail, ProcessListItem, WorkerDashboard } from "../types";

export const clientFixture: Client = {
  id: "client-1",
  name: "Cooperativa Vale do Norte",
  cpf_masked: "***.456.789-**",
  process_count: 1,
  communication_count: 3,
  pending_runs: 0,
  created_at: "2026-07-20T10:00:00Z",
};

export const processFixture: ProcessListItem = {
  id: "process-1",
  numero_processo: "00002827520248160131",
  formatted_number: "0000282-75.2024.8.16.0131",
  tribunal: "TJPR",
  process_class: "Execução de título extrajudicial",
  agency: "1ª Vara Cível de Pato Branco",
  external_link: "https://example.test/processo",
  cpf_status: "missing",
  polo: "A",
  association_status: "confirmed",
  association_reason: "Nome da parte confirmado",
  communications_count: 3,
  last_movement_at: "2026-07-28",
  datajud_status: "synced",
  datajud_synced_at: "2026-07-29T08:00:00Z",
  datajud_last_movement_at: "2026-07-28T14:00:00Z",
  process_parties: [
    { name: "Cooperativa Vale do Norte", polo: "A", source: "djen" },
    { name: "Marina Albuquerque", polo: "P", source: "datajud" },
  ],
  risk_matches_count: 1,
  highest_risk_level: "alto",
  risk_matches: [
    {
      id: "risk-match-1",
      keyword_id: "risk-1",
      keyword: "penhora",
      category: "Bloqueio judicial",
      risk_level: "alto",
      source: "texto",
      matched_text: "penhora",
      excerpt: "Foi determinada a penhora de ativos.",
      created_at: "2026-07-28T14:00:00Z",
    },
  ],
  phase_matches_count: 1,
  current_phase: {
    keyword_id: "phase-1",
    phase_key: "penhora",
    phase_name: "Penhora e constrição",
    phase_order: 50,
    keyword: "penhora",
    source: "datajud_movimento",
    matched_text: "penhora",
    excerpt: "Penhora de ativos",
    occurred_at: "2026-07-28T14:00:00Z",
  },
  phase_matches: [
    {
      keyword_id: "phase-1",
      phase_key: "penhora",
      phase_name: "Penhora e constrição",
      phase_order: 50,
      keyword: "penhora",
      source: "datajud_movimento",
      matched_text: "penhora",
      excerpt: "Penhora de ativos",
      occurred_at: "2026-07-28T14:00:00Z",
    },
  ],
};

export const processDetailFixture: ProcessDetail = {
  ...processFixture,
  datajud: {
    status: "synced",
    alias: "api_publica_tjpr",
    synced_at: "2026-07-29T08:00:00Z",
    source_updated_at: "2026-07-28T14:00:00Z",
    filed_at: "2024-01-15T12:00:00Z",
    last_movement_at: "2026-07-28T14:00:00Z",
    degree: "G1",
    secrecy_level: 0,
    system: "PROJUDI",
    format: "Eletrônico",
    subjects: ["Cédula de crédito bancário"],
    movements_count: 2,
    hit_count: 2,
    source_id: "source-record-1",
    candidate_source_id: null,
    selection_reason: "exact_match",
    review_reason: null,
    error: null,
    movements: [],
  },
  parties: [
    {
      id: "party-1",
      communication_id: "communication-1",
      name: "Cooperativa Vale do Norte",
      cpf_cnpj_masked: "**.***.***/****-12",
      polo: "A",
      is_client_match: true,
      cpf_status: "masked",
    },
  ],
  lawyers: [
    {
      id: "lawyer-1",
      name: "Helena Monteiro",
      oab_number: "43210",
      oab_state: "PR",
    },
  ],
  sources: [
    {
      id: "source-1",
      source: "DATAJUD",
      source_alias: "api_publica_tjpr",
      source_record_id: "source-record-1",
      numero_processo: processFixture.numero_processo,
      tribunal: "TJPR",
      degree: "G1",
      process_class: processFixture.process_class,
      agency: processFixture.agency,
      source_updated_at: "2026-07-28T14:00:00Z",
      filed_at: "2024-01-15T12:00:00Z",
      selected_for_cover: true,
      selection_reason: "exact_match",
      review_required: false,
    },
    {
      id: "source-2",
      source: "DATAJUD",
      source_alias: "api_publica_tjpr",
      source_record_id: "source-record-2",
      numero_processo: processFixture.numero_processo,
      tribunal: "TJPR",
      degree: "G2",
      process_class: "Agravo de instrumento",
      agency: "10ª Câmara Cível",
      source_updated_at: "2026-07-27T14:00:00Z",
      filed_at: "2025-02-10T12:00:00Z",
      selected_for_cover: false,
      selection_reason: null,
      review_required: true,
    },
  ],
  timeline: [
    {
      event_id: "event-1",
      process_id: processFixture.id,
      communication_id: null,
      source: "DATAJUD",
      source_record_id: "source-record-1",
      event_type: "procedural_movement",
      occurred_at: "2026-07-28T14:00:00Z",
      tribunal: "TJPR",
      degree: "G1",
      process_class: processFixture.process_class,
      agency: processFixture.agency,
      title: "Penhora de ativos",
      text: "Foi determinada a penhora de ativos financeiros da parte executada.",
      complements: ["SISBAJUD"],
      external_link: null,
      risk_matches: processFixture.risk_matches,
    },
    {
      event_id: "event-2",
      process_id: processFixture.id,
      communication_id: "communication-1",
      source: "DJEN",
      source_record_id: "communication-record-1",
      event_type: "publication",
      occurred_at: "2026-07-27T12:00:00Z",
      tribunal: "TJPR",
      degree: null,
      process_class: processFixture.process_class,
      agency: processFixture.agency,
      title: "Intimação",
      text: "Intimação da parte autora para manifestação.",
      complements: [],
      external_link: "https://example.test/publicacao",
      risk_matches: [],
    },
    {
      event_id: "event-3",
      process_id: processFixture.id,
      communication_id: null,
      source: "DATAJUD",
      source_record_id: "source-record-2",
      event_type: "procedural_movement",
      occurred_at: "2026-07-26T10:00:00Z",
      tribunal: "TJPR",
      degree: "G2",
      process_class: "Agravo de instrumento",
      agency: "10ª Câmara Cível",
      title: "Distribuição do recurso",
      text: "Recurso distribuído ao segundo grau.",
      complements: [],
      external_link: null,
      risk_matches: [],
    },
  ],
  djen_publications_count: 1,
  datajud_movements_count: 2,
  total_events: 3,
};

export const workerDashboardFixture: WorkerDashboard = {
  workers: [],
  active_workers: 0,
  working_workers: 0,
  idle_workers: 0,
  stale_workers: 0,
  queued_runs: 0,
  running_runs: 0,
  failed_runs: 0,
};
